### ISSUE TITLE
Possible words/locutions to check

### ISSUE THREAD

**Issue by Macxim** [kud/smack-my-twitter-bot#24]
Just to be clear, the first part before the `/`is the wrong word/locution.  
- ayeur / ailleurs
- "en faite" - "en faites" / "en fait"
- "en convaincant" / "en convainquant le jury"
- "diplome" / diplôme
- "aout" / "août"
- "ai aquis" - "ai aquit" / "ai acquis"
- "pallier à quelque chose" / "pallier quelque chose"
- "apeler" / "appeler"
- "répercutions" / "répercussions'
- "occurence" - "ocurrence" / "en l’occurrence"
- "language" / "langage"
- "le notre" / "le nôtre"
- "le votre" / "le vôtre"
- "exigent" / "exigeant"
- "dévelopement" / "développement"
- "entretient" / "entretien"
- "maintient" / "maintien"
- "soutient" / "soutien"
- "inclu(e)" / "inclus(e)"
- "emener" / "emmener"
- "ammener" / "amener"
- "crypter" / "chiffrer"
- "une demie-heure" / "une demi-heure"
- "une heure et demi" / "une heure et demie"

What do you think?

**Comment by kud** [comment]
le "vôtre" too so.

Perfect. ;)

**Comment by Macxim** [comment]
Right, added.

**Comment by Macxim** [comment]
[This](http://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Fautes_de_fran%C3%A7ais) could be interesting.
